### ISSUE TITLE
Action Dump Ignores creates

### ISSUE THREAD

**Issue by dpetzel** [bryanwb/chef-ark#14]
Per the documentation located here: http://community.opscode.com/cookbooks/ark it suggests that the dump action should honor the creates parameter. My testing seems to indicate that its not honor, and every single invocation results in the unzip command being called (as viewed with debug logging on)

Additionally, I was reviewing source, and I can see where cherry_pick combines path with the creates file https://github.com/bryanwb/chef-ark/blob/master/libraries/provider_ark.rb#L101

However looking at the similar block for dump: https://github.com/bryanwb/chef-ark/blob/master/libraries/provider_ark.rb#L43

I don't see where the creates file is considered.

FWIW, I am VERY new to both chef and ruby, so its possible I am missing something, but from what I've been able to gather, I believe this is a bug.

**Comment by bryanwb** [comment]
fixed, tks for reporting 
https://github.com/bryanwb/chef-ark/commit/053be52d74831be3efdc2ee3f116645bc0acdbc1
