### ISSUE TITLE
ark_provider doesn't support resource notifications

### ISSUE THREAD

**Issue by dpetzel** [bryanwb/chef-ark#15]
It appears that the ark_provider doesn't support notifications: http://wiki.opscode.com/display/chef/Resources#Resources-Notifications.

My use case is that I would like to restart a service after 'dumping' a ZIP. In the event that something was actually unzipped I would like to to do:
    notifies :restart, "service[MyService]", :immediately

**Comment by bryanwb** [comment]
lol, I am so dumb, I never thought of that. good point! should be too hard to add in

**Comment by bryanwb** [comment]
hey dude, I have added resource notifications. I am at a loss on how to test them properly. any ideas would be most welcome. Tests here: https://github.com/bryanwb/chef-ark/blob/master/files/default/tests/minitest/test_test.rb

https://github.com/bryanwb/chef-ark/commit/053be52d74831be3efdc2ee3f116645bc0acdbc1

I have not added resource notification for the make or configure actions, only the unpacking ones. For that reason I am leaving the ticket open. Thanks again for reporting the error! Looking forward to meeting you at Chefconf

**Comment by bryanwb** [comment]
done!
https://github.com/bryanwb/chef-ark/commit/68d77835f386bea87f0f88028b784135c970f50f

**Comment by dpetzel** [comment]
very cool, sorry I have not not had a chance to test this or the other fix you implemented for me. I've been pulled into a few other things, but hope to get back to this soon.
