### ISSUE TITLE
Autogen.sh as part for :configure

### ISSUE THREAD

**Issue by asergeyev** [bryanwb/chef-ark#16]
What if there would be small addition to :configure action that would run autogen.sh if configure does not exists? Would be nice to have something like that. IMO it should be part of configure but you might consider separate action for that.

**Comment by bryanwb** [comment]
asergeyev, I am not familiar w/ autogen.sh. Can you point me to some examples of applications that use it? I could experiment w/ it.

**Comment by asergeyev** [comment]
autogen is the script that generages "configure"   For example if you're using zeromq out of the development tree, not from officially released tarball https://github.com/zeromq/zeromq2-x, you need to run autogen first.

**Comment by bryanwb** [comment]
so u want to use ark to install zeromq? i'm down for that

**Comment by asergeyev** [comment]
Not necessarily. I have more software than just zeromq that need to run that script before configure. Right now I did action_autogen in my clone of ark but IMO it could be something like this:

<pre>
--- a/libraries/provider_ark.rb
+++ b/libraries/provider_ark.rb
@@ -58,10 +58,26 @@ class Chef
         action_link_paths
       end
 
-      def action_configure
+      def action_autogen
         set_paths
         action_download
         action_unpack
+        b = Chef::Resource::Script::Bash.new("autogen.sh to generate configure", run_context)
+        b.cwd new_resource.path
+        b.environment  new_resource.environment
+        b.code "./autogen.sh"
+        b.not_if{ ::File.exists?(::File.join(new_resource.path, 'configure')) }
+        b.run_action(:run)
+      end
+
+      def action_configure
+        if ::File.exists?(::File.join(new_resource.path, 'configure'))
+          action_autogen
+        else
+          set_paths
+          action_download
+          action_unpack
+        end
         b = Chef::Resource::Script::Bash.new("configure with autoconf", run_context)
         b.cwd new_resource.path
         b.new_resource.environment
</pre>

**Comment by bryanwb** [comment]
support added v0.0.10

@asergeyev, tks for your help!
