### ISSUE TITLE
strip_leading_dir option is not working

### ISSUE THREAD

**Issue by hgilani** [bryanwb/chef-ark#19]
Tested strip_leading_dir option with action install and it does not seem to be working. I am getting same results with this option turned on or off.

I drilled inside the code and following section of code seems to be culprit is what it boils down. If and else block seem to be working fine but both result in same directory structure.

```
      if new_resource.strip_leading_dir
        require 'tmpdir'
        tmpdir = Dir.mktmpdir
        cmd = Chef::ShellOut.new("unzip  -q -u -o '#{new_resource.release_file}' -d '#{tmpdir}'")
        cmd.run_command
        cmd.error!
        subdirectory_children = Dir.glob("#{tmpdir}/**")
        FileUtils.mv subdirectory_children, new_resource.path
        FileUtils.rm_rf tmpdir
      else
        cmd = Chef::ShellOut.new("unzip  -q -u -o #{new_resource.release_file} -d #{new_resource.path}")
        cmd.run_command
        cmd.error!
      end
```

**Comment by bryanwb** [comment]
That's definitely bug, am working on it

**Comment by bryanwb** [comment]
fixed https://github.com/bryanwb/chef-ark/commit/eb7c3ef377949055094c0542e9e50de75c0a3558
